# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    # not useful
    - exhaustivestruct # pointless
    - exhaustruct # pointless
    - gomnd # magic numbers are ok mostly
    - goerr113 # no need to wrap all errors, too much work
    # breaking things: https://github.com/atc0005/go-ci/issues/1024
    - depguard
    # todo: consider enabling:
    - testpackage
    - gochecknoglobals

linters-settings:
  gci:
    sections:
      - standard
      - default
      - localmodule
  goconst:
    min-occurrences: 5
    ignore-tests: true
